#!/bin/bash
# Build script for OpenBLAS on Windows
#
# Uses the environment variables
#
#  BUILD_BITS  (default binary architecture, 32 or 64, unspec -> 64).
#  INTERFACE64  (1 for 64-bit interface, anything else or undefined for 32,
#                This gives the default value if if_bits not specified above).
#  START_DIR  (directory containing OpenBLAS source, unspec -> .. from here)
#  LDFLAGS  (example: "-lucrt -static -static-libgcc")
#  PLAT (x86_64 or arm64)
#
# Expects at leasts these binaries installed from conda-forge
# zip, clang-cl, flang-new cmake, ninja

set -xe

build_bits="${BUILD_BITS:-64}}"
if [ "$INTERFACE64" == "1" ]; then if_default=64; else if_default=32; fi
if_bits=${2:-${if_default}}
echo "Binaries are $build_bits bit, interface is $if_bits bit"

cd OpenBLAS
git submodule update --init --recursive


# Get / clean code
git fetch origin
git checkout $(cat ../openblas_commit.txt)
git clean -fxd
git reset --hard

# Set architecture flags
if [ "$build_bits" == 64 ]; then
    march="x86-64"
    # https://csharp.wekeepcoding.com/article/10463345/invalid+register+for+.seh_savexmm+in+Cygwin
    extra="-fno-asynchronous-unwind-tables"
    vc_arch="X64"
    plat_tag="win_amd64"
    dynamic_list="PRESCOTT NEHALEM SANDYBRIDGE HASWELL SKYLAKEX"
    target=PRESCOTT
else
    march=pentium4
    extra="-mfpmath=sse -msse2"
    fextra="-m32"
    vc_arch="i386"
    plat_tag="win32"
    dynamic_list="PRESCOTT NEHALEM SANDYBRIDGE HASWELL"
    target=PRESCOTT
fi
if [ "$PLAT" == "arm64" ]; then
    CC=clang-cl
    FC=flang-new
    extra="-Wno-reserved-macro-identifier -Wno-unsafe-buffer-usage -Wno-unused-macros -Wno-sign-conversion -Wno-reserved-identifier"
    march=arm64
    target=ARMV8
    # This is quite minimal, may need to add NOEVERSEN1 and more?
    dynamic_list="ARMV8 CORTEXA57 NEOVERSEV1 THUNDERX"
fi

CC=clang-cl
FC=flang-new
cflags="-O2 -march=$march -mtune=generic $extra"
fflags="$fextra $cflags -frecursive -ffpe-summary=invalid,zero"

echo "using C compiler $(which $CC), --version:"
$CC --version
echo "using F compiler $(which $FC), --version:"
$FC --version
mkdir -p /c/temp
cp $(which llvm-mt.exe) /c/temp
/c/temp/llvm-mt.exe /?

# Set suffixed-ILP64 flags
if [ "$if_bits" == "64" ]; then
    LIBNAMESUFFIX="64_"
    interface_flags="-DINTERFACE64=1 -DSYMBOLSUFFIX=64_ -DLIBNAMESUFFIX=64_"
    # We override FCOMMON_OPT, so we need to set default integer manually
    fflags="$fflags -fdefault-integer-8"
else
    interface_flags=""
fi
# On windows, the LIBNAMEPREFIX is not needed, SYMBOLPREFIX is added to the lib
# name LIBPREFIX in Makefile.system.
interface_flags="$interface_flags -DSYMBOLPREFIX=scipy_ -DLIBNAMEPREFIX=scipy_ -DFIXED_LIBNAME=1"

# Build name for output library from gcc version and OpenBLAS commit.
GCC_TAG="gcc_$(gcc -dumpversion | tr .- _)"
OPENBLAS_VERSION=$(git describe --tags --abbrev=8)

# Patch OpenBLAS build to resolve all symbols and avoid linking
# with libquadmath
patch -p1 < ../patches-windows/openblas-make-libs.patch

mkdir build
cd build

# Build OpenBLAS
CFLAGS=$cflags
cmake .. -G Ninja \
 -DCMAKE_BUILD_TYPE=Release \
 -DTARGET=$target \
 -DYNAMIC_ARCH=1 \
 -DYNAMIC_LIST="$dynamic_list" \
 -DBINARY=$build_bits \
 -DBUFFERSIZE=20 \
 -DCMAKE_C_COMPILER=$CC \
 -DCMAKE_Fortran_COMPILER=$FC \
 -DBUILD_SHARED_LIBS=ON \
 -DCMAKE_SYSTEM_PROCESSOR=$march \
 -DCMAKE_MT=C:\\temp\\llvm-mt.exe \
 -DCMAKE_SYSTEM_NAME=Windows \
 -DSYMBOLPREFIX="scipy_" \
 -DLIBNAMEPREFIX="scipy_" \
 -DUSE_THREADS=1 \
 -DNUM_THREADS=24 \
  $interface_flags

ninja -j 16

cd ..

# Make sure quadmath library is not statically linked in to the DLL by checking
# the output.map generated by the linker when using `-Wl,-gc-sections -Wl,-s`
# the map will have libname(o-filename) for each function pulled out of the
# library libname
# The file itself appears in the map, so look for "libquadmath.a(". Use '-A 3'
# to show a bit of context if any symbols appear (which should not happen)
set +e
grep -A 2 "libquadmath.a(" exports/output.map
case $? in
  0)
    echo "link uses libquadmath.a when it should not"
    exit -1
  ;;
  1)
    if [ -f exports/output.map ]; then
      echo "Good, verified no 'libquadmath' used when linking"
    else
      echo "error occurred"
      exit -1
    fi
  ;;
  *)
    echo "grep returned $?, error occurred"
    exit -1
  ;;
esac
set -e


mv pkgconfig/*.pc pkgconfig/scipy-openblas.pc
if [ "$if_bits" == "64" ]; then
    sed -e "s/^Cflags.*/\0 -DBLAS_SYMBOL_PREFIX=scipy_ -DBLAS_SYMBOL_SUFFIX=64_/" -i pkgconfig/scipy-openblas.pc
else
    sed -e "s/^Cflags.*/\0 -DBLAS_SYMBOL_PREFIX=scipy_/" -i pkgconfig/scipy-openblas.pc
fi
ls build/lib

zip_name="openblas.zip"
zip -r $zip_name build
