name: Publish scipy_openblasN wheels

on:
  pull_request:
    branches:
      - main
      - maintenance/**
  workflow_dispatch:
    inputs:
      environment:
        description: Which PyPI environment to upload to, if any
        required: true
        type: choice
        options: [ "none", "testpypi", "pypi" ]


permissions:
  contents: read # to fetch code (actions/checkout)


jobs:
  call-posix:
    uses: ./.github/workflows/posix.yml

  #  call-windows:
  #    uses: ./.github/workflows/windows.yml
  #
  #  call-windows-arm:
  #    uses: ./.github/workflows/windows-arm.yml

  download-wheeks:
    runs-on: ubuntu-latest
    needs: [call-posix]

    - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        run-id: ${{ needs.call-posix.outputs.run_id }}
        pattern: wheels-*
        merge-multiple: true
        path: dist
  