name: Publish scipy_openblasN wheels

on:
  workflow_dispatch:
    inputs:
      environment:
        description: |
          Which PyPI environment to upload to?
          Be sure to push an annotated tag to 'main' before choosing 'pypi'
        required: true
        type: choice
        options: [ "none", "testpypi", "pypi" ]


permissions:
  contents: read # to fetch code (actions/checkout)


jobs:
# -------------------------------------------------------------------------------------
# Workflows to build wheels
  call-posix:
    uses: ./.github/workflows/posix.yml
    with:
      publish: true


  call-windows:
    uses: ./.github/workflows/windows.yml


  call-windows-arm:
    uses: ./.github/workflows/windows-arm.yml


# -------------------------------------------------------------------------------------
  check-version:
    name: Ensure commit is tag before upload to PyPi
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'pypi'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout openblas-libs
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true
          persist-credentials: false

      - name: Examine git commit
        run: |
          if [ -n "$(git tag --points-at HEAD)" ]; then
            echo "Current HEAD is tagged."
          else
            echo "Current HEAD is not tagged."
            exit 1
          fi
          

  test_pypi-publish:
    strategy:
      matrix:
        project: ["scipy-openblas32", "scipy-openblas64"]
    name: Publish ${{ matrix.project }} to TestPyPI
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'testpypi'
    needs: [call-posix, call-windows, call-windows-arm]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/${{ matrix.project }}/
    permissions:
      id-token: write  # mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          # I think the run-id for call-posix, call-windows, call-windows-arm should all be the same
          run-id: ${{ needs.call-posix.outputs.run_id }}
          pattern: wheels-*
          merge-multiple: true
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          print-hash: true
          attestations: true

  pypi-publish:
    name: Publish scipy-openblas to PyPI
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'pypi'
    needs: [call-posix, call-windows, call-windows-arm, check-version]
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write  # mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          run-id: ${{ needs.call-posix.outputs.run_id }}
          pattern: wheels-*
          merge-multiple: true
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          print-hash: true
          attestations: true
